// Taglines from thevisualist.org/about — “that happens to look like this:”
const TAGLINES = [
  "Always Open.",
  "What you need is, a place, a time, and some contact information",
  "Submit to us.",
  "You are here.",
  "Our community is really big.",
  "Let’s organize some culture together.",
  "Lets share.",
  "Three Sixty Five.",
  "You don’t need to know us to visit more often.",
  "You send us your stuff.",
  "Not to be confused with the take-out menus.",
  "Hard Core Smarty Neighborhood Stuff about Art.",
  "Don’t make us rhyme please.",
  "Archive Everything.",
  "Makes everything better.",
  "It’s your project.",
  "Gets more dates.",
  "Not in a box Not in a shoe.",
  "Starring Hugh Jackman.",
  "Walked into a bar. Ouch!",
  "It’s only dirt.",
  "Extra Credit for looking.",
  "Searches you’ll find.",
  "Makes it look easy",
  "We’re awed by your Mastery of Fine Arts.",
  "It’s a good day for sharing.",
  "We’re looking when you can’t.",
  "Luvs Spaces.org",
  "PoMo, PoCards",
  "We don’t sing so good.",
  "Because V is for so many other things too.",
  "Tastes like it sounds.",
  "Our time is your time.",
  "Nothing like the last show you missed.",
  "C’mon.",
  "Is it an exhibit if no one sees it?",
  "Let’s make a different kind of calendar",
  "The Visualist, The Visualist",
  "It goes with everything",
  "Follow Me.",
  "Hot live action for slow slow mail",
  "Your gallery likes people too",
  "Or V if you’re nasty.",
  "Are you gonna eat that?",
  "Because Spaces need Astronauts",
  "Loves your show.",
  "Knows it when it sees it.",
  "Likes Cats.",
  "Did the reading.",
  "Agrees with Sartre.",
  "Is not the last Rod Stewart Fan.",
  "Overslept",
  "Says, goodnight Gracie.",
  "Remembers Torpedo.",
  "Is handcrafted to fit right in.",
  "Kills nostalgia.",
  "Older than someone’s brother.",
  "Line Please?",
  "Tehee.",
  "Love’s your basement.",
  "We Art Chicago.",
  "Stands in line like the rest of us.",
  "One Chip, Two Chip, Red Chip (whatever)",
  "Drinks socially.",
  "Didn’t take the bus for the transfer",
  "Trusts",
  "Because you’re making history.",
  "Follows what came before.",
  "Eventing the wheel over and over",
  "Get the fuck out, see stuff.",
  "Chose funny and make things well",
  "Go Go Go",
  "Agrees and asks questions",
  "Look what we did here.",
  "Our emoji is more",
  "Often and Early.",
  "Is my name too.",
  "We’re in this because you’re in this",
  "For both day and evening.",
  "Marginalia for the soul.",
  "As common as any Tuesday gets.",
  "Is it Stray Off Course, or is it Stay of Course.",
  "No secrets, No sorrows.",
  "If you look for something you’ll find something here.",
  "Like a petting zoo for old bread.",
  "Drink up and get shit done.",
  "Reinventing New York one artist at a time",
  "Frodo lives.",
  "Over the mark but under the wire.",
  "Sunday’s aren’t our jam.",
  "Groks.",
  "This intentional archive for made-up things.",
  "Stinks of onions.",
  "Knows you’re out there.",
  "Like a one wing dove.",
  "No, alternative is not the gimmick.",
  "Not really uncomfortable, more like lived in.",
  "When there’s no “C” in cake.",
  "Unexamined or fearless",
  "Sweet generosity four walls and some action",
  "Slow down or pass already",
  "Other Site",
  "Then it’s winter again (grrr!!)",
  "Someone thinks you’ll like this.",
  "Putting you back in the list.",
  "Let’s do this.",
  "Performance Friendly.",
  "How can you have any pudding if you don’t eat your meat.",
  "Not entirely for social science research.",
  "The V should be silent.",
  "Let’s change stuff incrementally.",
  "We’ll make it fit.",
  "Following the same big bang as you.",
  "Or are you just happy to see me.",
  "Did you curate that content?",
  "What’s better than 3 seasons of Hardcastle and McCormick.",
  "Comics are Culture.",
  "Has a flower for you.",
  "Public Schools Public Minded",
  "Likes Danny the Street.",
  "Your movies are at the speed of life.",
  "Keep on saying Carpe Diem you idiot.",
  "Snacks are for trustees and shareholders, fuck snacks.",
  "Fry and Dry with each and every Wash.",
  "We’re not going to take it (if the artists aren’t listed).",
  "Change is not just for patrons.",
  "Just like you remember it only shorter.",
  "Sews mittens on everything.",
  "Isn’t wasting its vote.",
  "Is recovering nicely.",
  "Is under the gun.",
  "Will make it up in the straight away.",
  "Making due",
  "It’s your party.",
  "Mr Tate, Mr Slate, and Barbara Billingsly",
  "Dignity.",
  "Because the Reader was better.",
  "Your history is here.",
  "Even better this week",
  "Will press Eject and hand you the Tape.",
  "Never Closed.."
];

function randomTagline() {
  return TAGLINES[Math.floor(Math.random() * TAGLINES.length)];
}

window.TAGLINES = TAGLINES;
