#!/usr/bin/env python3
"""Generate 2026 tag data for the c3 site.

Writes two JS data files (script-src loadable, so file:// works without CORS):
  c3/tags2026.js      — TAGS_2026: [{n: name, s: slug, c: count}]
  c3/tagevents2026.js — TAG_EVENTS_2026: [{t, u, v, d, w: opening time, g: [tag slugs]}]

Run after refreshing the extract:
    python3 scripts/build_tag_data.py
"""

from __future__ import annotations

import json
import re
import unicodedata
from collections import Counter
from pathlib import Path

EVENTS_NDJSON = Path("data/processed/events.ndjson")
TOP_PICKS = Path("data/processed/top_picks_2026.json")
SITE_DIR = Path("/Users/brendan/Documents/c3")
YEAR = "2026"


def load_pick_ids() -> set[str]:
    if not TOP_PICKS.exists():
        return set()
    return {p["legacy_id"] for p in json.loads(TOP_PICKS.read_text(encoding="utf-8"))}


def slugify(name: str) -> str:
    name = unicodedata.normalize("NFKD", name).encode("ascii", "ignore").decode()
    return re.sub(r"-{2,}", "-", re.sub(r"[^a-z0-9]+", "-", name.lower())).strip("-")


def main() -> None:
    counts: Counter[str] = Counter()
    names: dict[str, str] = {}  # slug -> display name (first seen)
    pick_ids = load_pick_ids()
    events = []
    with EVENTS_NDJSON.open(encoding="utf-8") as f:
        for line in f:
            e = json.loads(line)
            if not (e.get("event_date") or "").startswith(YEAR):
                continue
            slugs = []
            for tag in e.get("tags", []):
                tag = tag.strip()
                slug = slugify(tag)
                if not tag or not slug:
                    continue
                names.setdefault(slug, tag)
                counts[slug] += 1
                slugs.append(slug)
            start = (e.get("opening_start_time_raw") or "").strip()
            end = (e.get("opening_end_time_raw") or "").strip()
            event = {
                "t": e.get("title", ""),
                "u": e.get("legacy_url") or e.get("source_url", ""),
                "v": e.get("venue_name", ""),
                "d": e.get("event_date", ""),
                "g": sorted(set(slugs)),
            }
            if start:
                event["w"] = f"{start} – {end}" if end else start
            for key, field in (("vu", "venue_url"), ("a", "address"),
                               ("m", "map_url"), ("o", "on_view_text")):
                value = (e.get(field) or "").strip()
                if value:
                    event[key] = value
            if e.get("legacy_id") in pick_ids:
                event["k"] = 1
                event["g"] = sorted(set(event["g"]) | {"top-pick"})
                names.setdefault("top-pick", "Top Pick")
                counts["top-pick"] += 1
            events.append(event)

    tags = [{"n": names[s], "s": s, "c": c}
            for s, c in sorted(counts.items(), key=lambda kv: (-kv[1], kv[0]))]

    (SITE_DIR / "tags2026.js").write_text(
        "// generated by visualist/scripts/build_tag_data.py\n"
        f"const TAGS_2026 = {json.dumps(tags, ensure_ascii=False)};\n",
        encoding="utf-8")
    (SITE_DIR / "tagevents2026.js").write_text(
        "// generated by visualist/scripts/build_tag_data.py\n"
        f"const TAG_EVENTS_2026 = {json.dumps(events, ensure_ascii=False)};\n",
        encoding="utf-8")
    print(f"{len(events)} events, {len(tags)} tags -> tags2026.js "
          f"({(SITE_DIR / 'tags2026.js').stat().st_size // 1024}K), tagevents2026.js "
          f"({(SITE_DIR / 'tagevents2026.js').stat().st_size // 1024}K)")


if __name__ == "__main__":
    main()
